### ISSUE TITLE
Update for Foundry V11

### ISSUE THREAD

**Issue by nschoenwald** [Larkinabout/fvtt-combat-chat#1]
I think the module works fine as is for Foundry V11, but I have not had the chance for extensive tests yet. Either way, it would be great if the module could be updated, even if it's just the verified compatibility in the manifest.

**Comment by Larkinabout** [comment]
It's on the to-do list, but I have a few tweaks I want to add at the same time.

**Comment by Larkinabout** [comment]
Added in Combat Chat 1.1.0.
