### ISSUE TITLE
Having issues with it not working

### ISSUE THREAD

**Issue by Zarhog** [Larkinabout/fvtt-combat-chat#2]
Hay im not sure what im doing worong but in V11 this modual seems be not be working somtimes, the chat just dosnt show in the combat tab
![image](https://github.com/Larkinabout/fvtt-combat-chat/assets/76391362/911fbf9e-e194-49a9-a48b-fbc09f233eec)
[v.tcrvtt.com-1695235682020.log](https://github.com/Larkinabout/fvtt-combat-chat/files/12676580/v.tcrvtt.com-1695235682020.log)

**Comment by Larkinabout** [comment]
Make sure at least Chat Log Display is enabled in the module settings.

![image](https://github.com/Larkinabout/fvtt-combat-chat/assets/105953297/6548e94c-a7ee-4482-9d0a-66ed41973e2e)

**Comment by Zarhog** [comment]
it was sorry about the late reply
